const data = {
  status: '0',
  message: 'success',
  data: [
    {
      id: 2291,
      pId: 0,
      name: '水质实验室',
      url: 'http://192.168.10.250/cloud_test/jiajiang/water-laboratory-ui/#/',
      prefix: 'water-laboratory',
      type: 0,
      menuIcon: 'icon-yun icon-yun_usericon_szy',
      nameEn: 'water-laboratory',
      sort: 1,
      serverType: 1,
      serviceGroup: '1',
      router: '',
      title: '水质实验室',
      logo: 'icon',
      favicon: 'icon',
      children: [
        {
          id: 2292,
          pId: 2291,
          name: '常规填报',
          url: 'general-report',
          prefix: 'water-laboratory',
          type: 0,
          menuIcon: 'general-report',
          nameEn: 'general-report',
          sort: 1,
          serverType: 1,
          serviceGroup: '1',
          router: 'general-report',
          title: '',
          logo: '',
          favicon: '',
          children: [
            {
              id: 2293,
              pId: 2292,
              name: '水源水日检',
              url: 'water-daily-list',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: 'water-daily-list',
              nameEn: 'water-daily-list',
              sort: 1,
              serverType: 1,
              serviceGroup: '1',
              router: 'water-daily-list',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
            {
              id: 2294,
              pId: 2292,
              name: '水源水月检',
              url: 'water-monthly-list',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: 'water-monthly-list',
              nameEn: 'water-monthly-list',
              sort: 2,
              serverType: 1,
              serviceGroup: '1',
              router: 'water-monthly-list',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
            {
              id: 2315,
              pId: 2292,
              name: '沉淀、过滤净化工序',
              url: 'purification-process-list',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: 'purification-process-list',
              nameEn: 'purification-process-list',
              sort: 3,
              serverType: 1,
              serviceGroup: '1',
              router: 'purification-process-list',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
            {
              id: 3346,
              pId: 2292,
              name: '出厂水在线监测',
              url: 'water-online-monitoring-list',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: 'water-online-monitoring-list',
              nameEn: 'water-online-monitoring-list',
              sort: 4,
              serverType: 1,
              serviceGroup: '1',
              router: 'water-online-monitoring-list',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
            {
              id: 3347,
              pId: 2292,
              name: '出厂水日检',
              url: 'factory-daily-inspection-list',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: 'factory-daily-inspection-list',
              nameEn: 'factory-daily-inspection-list',
              sort: 5,
              serverType: 1,
              serviceGroup: '1',
              router: 'factory-daily-inspection-list',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
            {
              id: 3348,
              pId: 2292,
              name: '出厂水月检',
              url: 'factory-monthly-inspection-list',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: 'factory-monthly-inspection-list',
              nameEn: 'factory-monthly-inspection-list',
              sort: 6,
              serverType: 1,
              serviceGroup: '1',
              router: 'factory-monthly-inspection-list',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
            {
              id: 2334,
              pId: 2292,
              name: '管网水半月检',
              url: 'half-month-inspection-list',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: 'half-month-inspection-list',
              nameEn: 'half-month-inspection-list',
              sort: 7,
              serverType: 1,
              serviceGroup: '1',
              router: 'half-month-inspection-list',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
            {
              id: 3349,
              pId: 2292,
              name: '管网末梢水月检',
              url: 'month-inspection-list',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: 'month-inspection-list',
              nameEn: 'month-inspection-list',
              sort: 8,
              serverType: 1,
              serviceGroup: '1',
              router: 'month-inspection-list',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
          ],
        },
        {
          id: 3361,
          pId: 2291,
          name: '特殊填报',
          url: 'special-report',
          prefix: 'water-laboratory',
          type: 0,
          menuIcon: 'special-report',
          nameEn: 'special-report',
          sort: 2,
          serverType: 1,
          serviceGroup: '1',
          router: 'special-report',
          title: '',
          logo: '',
          favicon: '',
          children: [
            {
              id: 3362,
              pId: 3361,
              name: '水源水日检',
              url: 'special-water-daily-list',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: 'special-water-daily-list',
              nameEn: 'special-water-daily-list',
              sort: 1,
              serverType: 1,
              serviceGroup: '1',
              router: 'special-water-daily-list',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
            {
              id: 3363,
              pId: 3361,
              name: '水源水月检',
              url: 'special-water-monthly-list',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: 'special-water-monthly-list',
              nameEn: 'special-water-monthly-list',
              sort: 2,
              serverType: 1,
              serviceGroup: '1',
              router: 'special-water-monthly-list',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
            {
              id: 3364,
              pId: 3361,
              name: '沉淀、过滤净化工序',
              url: 'special-purification-process-list',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: 'special-purification-process-list',
              nameEn: 'special-purification-process-list',
              sort: 3,
              serverType: 1,
              serviceGroup: '1',
              router: 'special-purification-process-list',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
            {
              id: 3365,
              pId: 3361,
              name: '出厂水在线监测',
              url: 'special-water-online-monitoring-list',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: 'special-water-online-monitoring-list',
              nameEn: 'special-water-online-monitoring-list',
              sort: 4,
              serverType: 1,
              serviceGroup: '1',
              router: 'special-water-online-monitoring-list',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
            {
              id: 3366,
              pId: 3361,
              name: '出厂水日检',
              url: 'special-factory-daily-inspection-list',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: 'special-factory-daily-inspection-list',
              nameEn: 'special-factory-daily-inspection-list',
              sort: 5,
              serverType: 1,
              serviceGroup: '1',
              router: 'special-factory-daily-inspection-list',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
            {
              id: 3367,
              pId: 3361,
              name: '出厂水月检',
              url: 'special-factory-monthly-inspection-list',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: 'special-factory-monthly-inspection-list',
              nameEn: 'special-factory-monthly-inspection-list',
              sort: 6,
              serverType: 1,
              serviceGroup: '1',
              router: 'special-factory-monthly-inspection-list',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
            {
              id: 3368,
              pId: 3361,
              name: '管网末梢水月检',
              url: 'special-month-inspection-list',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: 'special-month-inspection-list',
              nameEn: 'special-month-inspection-list',
              sort: 7,
              serverType: 1,
              serviceGroup: '1',
              router: 'special-month-inspection-list',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
            {
              id: 3369,
              pId: 3361,
              name: '管网水半月检',
              url: 'special-half-month-inspection-list',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: 'special-half-month-inspection-list',
              nameEn: 'special-half-month-inspection-list',
              sort: 8,
              serverType: 1,
              serviceGroup: '1',
              router: 'special-half-month-inspection-list',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
          ],
        },
        {
          id: 2309,
          pId: 2291,
          name: '数据审核',
          url: 'audit',
          prefix: 'water-laboratory',
          type: 0,
          menuIcon: 'audit',
          nameEn: 'audit',
          sort: 3,
          serverType: 1,
          serviceGroup: '1',
          router: 'audit',
          title: '',
          logo: '',
          favicon: '',
          children: [
            {
              id: 2310,
              pId: 2309,
              name: '常规检测审核',
              url: 'regular-aduit',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: 'regular-aduit',
              nameEn: 'regular-aduit',
              sort: 1,
              serverType: 1,
              serviceGroup: '1',
              router: 'regular-aduit',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
            {
              id: 3370,
              pId: 2309,
              name: '特殊检测审核',
              url: 'special-aduit',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: 'special-aduit',
              nameEn: 'special-aduit',
              sort: 2,
              serverType: 1,
              serviceGroup: '1',
              router: 'special-aduit',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
          ],
        },
        {
          id: 2311,
          pId: 2291,
          name: '原数据查看',
          url: 'basic-data',
          prefix: 'water-laboratory',
          type: 0,
          menuIcon: 'basic-data',
          nameEn: 'basic-data',
          sort: 4,
          serverType: 1,
          serviceGroup: '1',
          router: 'basic-data',
          title: '',
          logo: '',
          favicon: '',
          children: [
            {
              id: 2312,
              pId: 2311,
              name: '常规检测报告',
              url: 'basic-data-regular',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: 'basic-data-regular',
              nameEn: 'basic-data-regular',
              sort: 1,
              serverType: 1,
              serviceGroup: '1',
              router: 'basic-data-regular',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
            {
              id: 3371,
              pId: 2311,
              name: '特殊检测报告',
              url: 'special-basic-data-regular',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: 'special-basic-data-regular',
              nameEn: 'special-basic-data-regular',
              sort: 2,
              serverType: 1,
              serviceGroup: '1',
              router: 'special-basic-data-regular',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
          ],
        },
        {
          id: 2313,
          pId: 2291,
          name: '报表查看',
          url: 'report-view',
          prefix: 'water-laboratory',
          type: 0,
          menuIcon: 'report-view',
          nameEn: 'report-view',
          sort: 5,
          serverType: 1,
          serviceGroup: '1',
          router: 'report-view',
          title: '',
          logo: '',
          favicon: '',
          children: [
            {
              id: 2314,
              pId: 2313,
              name: '常规检测报告查阅',
              url: 'report-view-regular',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: 'report-view-regular',
              nameEn: 'report-view-regular',
              sort: 1,
              serverType: 1,
              serviceGroup: '1',
              router: 'report-view-regular',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
            {
              id: 3372,
              pId: 2313,
              name: '特殊水质检测报告查阅',
              url: 'report-view-special',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: 'report-view-special',
              nameEn: 'report-view-special',
              sort: 2,
              serverType: 1,
              serviceGroup: '1',
              router: 'report-view-special',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
            {
              id: 2316,
              pId: 2313,
              name: '报送水务局',
              url: 'report-view-waterBoard',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: 'report-view-waterBoard',
              nameEn: 'report-view-waterBoard',
              sort: 3,
              serverType: 1,
              serviceGroup: '1',
              router: 'report-view-waterBoard',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
            {
              id: 2317,
              pId: 2313,
              name: '报送疾控中心及卫生执法大队',
              url: 'report-view-cdc',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: 'report-view-cdc',
              nameEn: 'report-view-cdc',
              sort: 4,
              serverType: 1,
              serviceGroup: '1',
              router: 'report-view-cdc',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
          ],
        },
        {
          id: 3351,
          pId: 2291,
          name: '知识库',
          url: 'zhishiku',
          prefix: 'water-laboratory',
          type: 0,
          menuIcon: 'zhishiku',
          nameEn: 'zhishiku',
          sort: 6,
          serverType: 1,
          serviceGroup: '1',
          router: 'zhishiku',
          title: '',
          logo: '',
          favicon: '',
          children: [
            {
              id: 3352,
              pId: 3351,
              name: '目录',
              url: '/knowlege-docdirectory',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: '/knowlege-docdirectory',
              nameEn: '/knowlege-docdirectory',
              sort: 1,
              serverType: 1,
              serviceGroup: '1',
              router: '/knowlege-docdirectory',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
            {
              id: 3353,
              pId: 3351,
              name: '查看',
              url: '/knowlege-article',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: '/knowlege-article',
              nameEn: '/knowlege-article',
              sort: 2,
              serverType: 1,
              serviceGroup: '1',
              router: '/knowlege-article',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
            {
              id: 3354,
              pId: 3351,
              name: '审核',
              url: 'knowlege-docaudit',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: 'knowlege-docaudit',
              nameEn: 'knowlege-docaudit',
              sort: 3,
              serverType: 1,
              serviceGroup: '1',
              router: 'knowlege-docaudit',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
          ],
        },
        {
          id: 2307,
          pId: 2291,
          name: '设置',
          url: 'http://www.baidu.com',
          prefix: 'water-laboratory',
          type: 0,
          menuIcon: 'system',
          nameEn: 'system',
          sort: 7,
          serverType: 1,
          serviceGroup: '1',
          router: 'http://www.baidu.com',
          title: '',
          logo: '',
          favicon: '',
          children: [
            {
              id: 2308,
              pId: 2307,
              name: '检测点管理',
              url: 'test-points',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: 'test-points',
              nameEn: 'test-points',
              sort: 1,
              serverType: 1,
              serviceGroup: '1',
              router: 'test-points',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
            {
              id: 3344,
              pId: 2307,
              name: '日志',
              url: 'report-log',
              prefix: 'water-laboratory',
              type: 0,
              menuIcon: 'report-log',
              nameEn: 'report-log',
              sort: 2,
              serverType: 1,
              serviceGroup: '1',
              router: 'report-log',
              title: '',
              logo: '',
              favicon: '',
              children: [],
            },
          ],
        },
      ],
    },
  ],
};
export default data;
